### ISSUE TITLE
Make the site more NoScript friendly

### ISSUE THREAD

**Issue by danry25** [ProjectMeshnet/website#2]
[It appears the whole site breaks down when using NoScript](http://www.reddit.com/r/technology/comments/1gdsy3/google_introduces_project_loon_balloonpowered/cajeha5?context=3), since the CSS doesn't load properly and even unblocking projectmeshnet.og in NoScript didn't fix this issue. Being accessible to security minded clients running NoScript would be ideal, even if it means breakage of some features like the embedded youtube video, etc.

**Comment by dansup** [comment]
This has been fixed in recent update, javascript is required for dropdown menu on mobile and Coinbase modal popup, however it will still act like a normal button for people with disabled javascript.
