### ISSUE TITLE
Add navbar to blog

### ISSUE THREAD

**Issue by dansup** [ProjectMeshnet/website#3]
From /r/darknetplan, [this](http://www.reddit.com/r/darknetplan/comments/1m7k4q/new_project_meshnet_website/cc6p3k3) got me thinking that perhaps we should migrate from wordpress.com to our own blog (say projectmeshnet.org/blog) and create a custom theme based on the new layout. @lukevers Thoughts?

**Comment by lukevers** [comment]
I would much prefer that, and I'd be glad to put that together, too.

**Comment by dansup** [comment]
Ping me on irc and we'll work something out.
